services:
  scheduler:
    image: mageai/mageai
    volumes:
      - "./scheduler_data:/home/src"
    ports:
      - "8085:8085"
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler
    

    